version: 0.0.1.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - dev
image: Visual Studio 2017
platform: x64
before_build:
- cmd: nuget restore
build:
  project: ClassicUO.sln
  verbosity: minimal
artifacts:
- path: /bin/
  name: ClassicUO
deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: ClassicUO-dev-release
  description: 'Appveyor autodeploy.\nThis build may not be safe: use it at your own risk.\nIt does not contain Razor.'
  auth_token:
    secure: lNz2TIidQg+skkpc3OL8cnC0dd5Yj/y9Xtb9KgJUkGTFRuxft41IE+kiDmZ2ugJdH8vAPItVe2pycqfUFvluTjnn3ZjxpY4oErxU3/ylHdw=
  draft: true
  force_update: true
  on:
    branch: dev
